version: 0.2

phases:
  pre_build:
    commands:
      - pip3 install awscli --upgrade --user
      - export AWS_ACCOUNT=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
      - aws codeartifact login --tool pip --domain opendna --domain-owner 921320062099 --repository opendna-$ENV
  build:
    commands:
      # setup virtualenv
      - virtualenv -p python3.8 venv
      - . venv/bin/activate

      - pip install -r requirements.txt
      - pip install -r requirements_docs.txt
      - make docs

      - export OUT_FILE="docs-${CODEBUILD_RESOLVED_SOURCE_VERSION}.tar.gz"
      - export S3_PATH="s3://${S3_BUCKET}/${S3_PREFIX}/${CODEBUILD_RESOLVED_SOURCE_VERSION}/"
      - tar -cvzf ${OUT_FILE} docs/build
      - aws s3 cp ${OUT_FILE} ${S3_PATH}
      - printf '{"DocsZip":"%s"}' "${S3_PATH}${OUT_FILE}" > build.json
      - cat build.json
artifacts:
  files:
    - ./build.json
    - ./aws/buildspecs/buildspec-docs-deploy.yml
