version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.12
  pre_build:
    commands:
      - pip3 install awscli --upgrade --user
      - export AWS_ACCOUNT=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
      - aws codeartifact login --tool pip --domain opendna --domain-owner 921320062099 --repository opendna-$ENV
  build:
    commands:
      # setup virtualenv
      - python3.12 -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip

      - pip install -r requirements.txt
      - pip install -r requirements_test.txt

#      - make coverage
#
#      - export OUT_FILE="coverage-${CODEBUILD_RESOLVED_SOURCE_VERSION}.tar.gz"
#      - export S3_PATH="s3://${S3_BUCKET}/${S3_PREFIX}/${CODEBUILD_RESOLVED_SOURCE_VERSION}/"
#      - tar -cvzf ${OUT_FILE} ./htmlcov
#      - aws s3 cp ${OUT_FILE} ${S3_PATH}
#      - printf '{"CovZip":"%s"}' "${S3_PATH}${OUT_FILE}" > build.json
#      - cat build.json
#artifacts:
#  files:
#    - ./build.json
#    - ./buildspecs/buildspec-coverage-deploy.yml
