version: 0.2

phases:
  pre_build:
    commands:
      - pip3 install awscli --upgrade --user
      - export AWS_ACCOUNT=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
      - aws codeartifact login --tool pip --domain opendna --domain-owner 921320062099 --repository opendna-$ENV
  build:
    commands:
      # setup virtualenv
      - python3.12 -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip

      - printenv
      - cd src
      - pip install --upgrade pip
      - pip install -r ../requirements.txt

      - export S3_KEY="${S3_PREFIX}/${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - export LAMBDA_KEY="${S3_KEY}/lambda-package-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip"

      - mkdir -p /tmp/lambda_package
      - cp -r * /tmp/lambda_package/
      - cp -r ../venv/lib/python3.12/site-packages/* /tmp/lambda_package/
      - cd /tmp/lambda_package
      - zip -r9 ../lambda-package.zip .

      - aws s3 cp /tmp/lambda-package.zip s3://$S3_BUCKET/$LAMBDA_KEY
      - cd ..
      - printf '{"Lambda":"%s", "ArtifactsLocation":"%s"}' $LAMBDA_KEY $S3_KEY > build.json
      - cat build.json

      # copy deploy master to tmp folder, later on placed in artifacts
      - aws s3 cp ${S3_TEMPLATES_LOCATION}/deploy-master.yml /tmp/deploy-master.yml

artifacts:
  files:
    - /tmp/deploy-master.yml
    - src/build.json
  discard-paths: yes
